name: download-sigbm  # Nome descritivo do workflow

on:
  # Agendamento para execução diária às 08h (horário de Brasília = UTC-3, logo 11h UTC)
  schedule:
    - cron: '0 11 * * *'
  # Permite execução manual através da interface do GitHub
  workflow_dispatch:

jobs:
  download_excel:
    runs-on: ubuntu-latest  # Ambiente Linux

    steps:
      # Faz o checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Cria a pasta "data" caso não exista
      - name: Criar pasta data
        run: mkdir -p data

      # Faz o download do arquivo Excel via POST e salva com timestamp no nome
      - name: Baixar arquivo Excel do SIGBM via POST
        run: |
          # Define a data atual no formato AAAA-MM-DD
          DATE=$(date +"%Y-%m-%d")
          # Define o nome do arquivo incluindo a data
          FILENAME="data/sigbm_${DATE}.xlsx"
          # Executa o download via método POST com curl e salva o arquivo na pasta data
          curl --insecure -X POST "https://app.anm.gov.br/SIGBM/Publico/ClassificacaoNacionalDaBarragem/ExportarExcel" -o "$FILENAME"
          echo "Arquivo baixado em: $FILENAME"

      # Configura o Git, faz commit e push dos arquivos atualizados
      - name: Commit e Push dos arquivos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configura o nome e email para o commit conforme solicitado
          git config --local user.email "milz.bea@gmail.com"
          git config --local user.name "Beatriz Milz"
          # Adiciona os arquivos da pasta data
          git add data/
          # Verifica se há mudanças a serem commitadas
          if git diff --staged --quiet; then
            echo "Sem alterações para commit."
          else
            # Cria commit com mensagem e data atual
            git commit -m "Atualiza arquivo Excel SIGBM - $(date +"%Y-%m-%d")"
            git push
          fi
